### ISSUE TITLE
lua（app）模块重新加载

### ISSUE THREAD

**Issue by littlecxm** [chenxuuu/receiver-meow#20]
现在lua模块更新后不能实时reload？
之前的修改的话是立即生效的，现在貌似要重启整个receiver-meow插件？

**Comment by chenxuuu** [comment]
因为更改为了task模式，只有启动之后会加载文件内容


打开插件菜单，里面有重载虚拟机的按键



---原始邮件---
发件人: "CXM"<notifications@github.com&gt;
发送时间: 2020年6月8日(周一) 凌晨0:29
收件人: "chenxuuu/receiver-meow"<receiver-meow@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [chenxuuu/receiver-meow] lua（app）模块重新加载 (#20)




 
现在lua模块更新后不能实时reload？
 之前的修改的话是立即生效的，现在貌似要重启整个receiver-meow插件？

**Comment by littlecxm** [comment]
got it
